/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import java.io.File;
import javafx.application.Platform;
import javafx.beans.binding.Bindings;
import javafx.beans.property.DoubleProperty;
import javafx.embed.swing.JFXPanel;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.GroupLayout.Group;

/**
 *
 * @author HP
 */
public class panelVideo extends javax.swing.JPanel {

    private final JFXPanel jfxPanel = new JFXPanel();
    public MediaPlayer mediaPlayer;
    @FXML
    private MediaView mediaView;

    public panelVideo() {
        initComponents();
        createScene();
        panelVideo.add(jfxPanel);
    }

    public void createScene() {
        Platform.runLater(new Runnable() {

            @Override
            public void run() {
                File file = new File("C:\\Java-JSP\\duan9\\src\\video\\The D Song Lowercase  Super Simple ABCs.mp4");
                MediaPlayer oracleVid = new MediaPlayer(
                        new Media(file.toURI().toString())
                );

                jfxPanel.setScene(new Scene(new javafx.scene.Group(new MediaView(oracleVid))));

                oracleVid.setVolume(0.7);
                oracleVid.setCycleCount(MediaPlayer.INDEFINITE);
                oracleVid.play();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelVideo = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelVideo.setPreferredSize(new java.awt.Dimension(900, 700));
        panelVideo.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelVideo, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelVideo;
    // End of variables declaration//GEN-END:variables
}
